### ISSUE TITLE
ts ECMAScript  Consider using 'export default' 

### ISSUE THREAD

**Issue by zbcms** [faker-js/faker#245] opened 2022-01-20 14:02 UTC
./node_modules/@faker-js/faker/index.ts:4:1
Type error: Export assignment cannot be used when targeting ECMAScript modules. Consider using 'export default' or another module format instead.

  2 | import { Faker } from './lib';
  3 | const faker: Faker = new Faker({ locales: require('./lib/locales') });
> 4 | export = faker;
    | ^

update:
export default faker;

**Comment by Shinigami92** [comment] 2022-01-20 14:06
Duplicate of #217 

We are already on it :slightly_smiling_face:

**Comment by Shinigami92** [comment] 2022-01-20 14:06
Will leave this open, so no more folks are creating multiple duplicates

**Comment by Shinigami92** [comment] 2022-01-28 12:55
We released 6.0.0-alpha.5 and this should be fixed

**Closed by Shinigami92** 2022-01-28 12:55 UTC
Labels: duplicate, enhancement
