### ISSUE TITLE
New methods not supported by helpers.fake()

### ISSUE THREAD

**Issue by jezzdk** [faker-js/faker#2192] opened 2023-05-31 11:09 UTC
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

I'm trying to use the helpers.fake() method with a string saved in my database. 
I've saved `airline.airline().name`, as described [in the docs](https://fakerjs.dev/api/airline.html), in my database.
However, some of the new methods in v8, like the one above, returns objects and those are not supported in the fake() method.

Usage: 
```
faker.helpers.fake(`Airline: {{airline.airline().name}}`);
```

Result: 
```
airline.airline().name Error: Invalid module method or definition: airline.airline.name
- faker.airline.airline.name is not a function
- faker.definitions.airline.airline.name is not an array
```

Expected:
```
Airline: American Airlines
```

### Minimal reproduction code

https://stackblitz.com/edit/faker-js-demo-hpw22c?file=index.ts

### Environment Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 273.97 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    npm: 9.6.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.3
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by matthewmayer** [comment] 2023-05-31 13:33
Instead of
```
faker.helpers.fake(`Airline: {{airline.airline().name}}`);
```

You can use
```
`Airline: ${faker.airline.airline().name}`
```
[edit: fixed]

**Comment by matthewmayer** [comment] 2023-05-31 13:34
Note this is duplicate of https://github.com/faker-js/faker/issues/1850

**Comment by jezzdk** [comment] 2023-05-31 13:43
> Instead of
> 
> ```
> faker.helpers.fake(`Airline: {{airline.airline().name}}`);
> ```
> 
> You can use
> 
> ```
> `Airline: {{faker.airline.airline().name}}`
> ```

I'm guessing you mean:
```
`Airline: ${faker.airline.airline().name}`
```

Although that won't help since the method name is a string from the db.

**Comment by jezzdk** [comment] 2023-05-31 13:43
> Note this is duplicate of #1850

That's true. I'll watch that one instead :)

**Comment by ST-DDT** [comment] 2023-05-31 15:04
I'm closing this as a duplicate of #1850 .

But if you are willing to take on the original issue, feel free to do so. If you leave a comment there I can assign that issue to you.

**Closed as not planned by ST-DDT** 2023-05-31 15:04 UTC
Labels: c: bug, s: invalid, duplicate
