### ISSUE TITLE
Rename number.float precision to something more meaningfull

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1591] opened 2022-11-22 18:34 UTC
I currently think about the `precision` value now changed...
This could come into confusion when using it with native JS as there it has another meaning: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toPrecision#parameters

> An integer specifying the number of **significant** digits.

It's different to what e.g. `toFixed` is doing: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#parameters

> The number of digits to appear **after the decimal point**

So we might want to rename it, or do alternative ways :thinking:
I'm also not sure if we e.g. accept negative exponents, but this might work but lead just to more _roundings_

**Comment by ST-DDT** [comment] 2022-12-09 16:55
Duplicate of #1596

- #1596

**Closed as completed by ST-DDT** 2022-12-09 16:55 UTC
Labels: p: 1-normal, c: refactor, duplicate, m: number
