### ISSUE TITLE
Deprecate helpers.createTransaction() 

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#782] opened 2022-04-05 20:47 UTC
### Clear and concise description of the problem

The method provides a range of methods that are loosely related to each other.
Most users will usually require more specific data models or other property names.

### Suggested solution

The method should be deprecated for removal similar to the card methods.

### Alternative

Upgrade the method to create transactions for the current/recent/future date.

**Comment by Shinigami92** [comment] 2022-04-05 20:50
We can safely remove the `s: needs decision` because this was just forgotten to be marked as deprecated.
I assume I just searched for `card*` stuff.

**Comment by Shinigami92** [comment] 2022-05-04 10:40
closed via #916 
I removed it intentionally because I do not think that anyone uses it
Even if, they should create their own function

**Closed by Shinigami92** 2022-05-04 10:40 UTC
Labels: good first issue, c: chore, p: 1-normal, s: accepted

**Comment by robross0606** [comment] 2024-05-31 15:38
We we use it.  LOL.  It would be nice if there were deprecation notes with a recommended alternative approach.

**Comment by Shinigami92** [comment] 2024-05-31 16:59
> We we use it.  LOL.  It would be nice if there were deprecation notes with a recommended alternative approach.

Thanks 🙏 
That's valuable feedback. Can you provide some more context so we can see how you used it.
We once decided to not provide "complex" objects as result anymore so faker-consumers just build there own functions wrapping faker.
Can we help you somehow with this?

**Comment by ST-DDT** [comment] 2024-05-31 19:32
> It would be nice if there were deprecation notes with a recommended alternative approach.

We have improved our upgrading guideline rules in the meantime.
Could you please check whether the new migration guide would satisfy your requirements?

https://next.fakerjs.dev/guide/upgrading.html

---

We removed these methods because the requirements for the complex return objects differ between most users and thus an individualistic approach with these methods usually results in better usability. We are sorry for the inconvenience that was caused by this change.

Here is a workaround, that you can use as an alternative to the built-in method:

````ts
function createTransaction(): {
  amount: string;
  date: Date;
  business: string;
  name: string;
  type: string;
  account: string;
} {
  return {
    amount: faker.finance.amount(),
    date: faker.date.recent(),
    business: faker.company.name(),
    name: `${faker.finance.accountName()} (...${faker.string.numeric(4)})`,
    type: faker.helpers.arrayElement(
      faker.definitions.finance.transaction_type
    ),
    account: faker.finance.accountNumber(),
  };
}
````

Tested with `v8.4.1`:

````js
{
  amount: '428.32',
  date: 2024-05-30T20:17:49.443Z,
  business: 'Hodkiewicz, Gottlieb and Effertz',
  name: 'Savings Account (...7362)',
  type: 'withdrawal',
  account: '96287636'
}
````

**Comment by robross0606** [comment] 2024-05-31 19:37
The missing thought process here is that someone upgrading the library with pre-existing usage needs to go hunt down how to satisfy previous behavior to not break existing behavior.  That means understanding what was being done in the built-in method and then mimicking it.  I was able to do this, but it required digging into the (now removed) code to see how it was done.  The [migration notes](https://v7.fakerjs.dev/guide/upgrading.html#deprecated-methods-removed) basically don't account for this use case at all, amounting to "You're on your own.  Do what you need.".  What we needed is to reproduce what was being done in the old version so as to not break pre-existing behavior.

**Comment by matthewmayer** [comment] 2024-05-31 22:04
I think this has something which has improved over time. The 6 to 7 migration guide was quite terse. 7 to 8 and the upcoming 8 to 9 migration guides are hopefully better about providing explicit alternatives for removed functionality.
