### ISSUE TITLE
fullName uses fallback first names in el (Greek)

### ISSUE THREAD

**Issue by matthewmayer** [faker-js/faker#1553] opened 2022-11-13 06:12 UTC
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

faker.person.fullName() appears to always fall back to English first names, while faker.person.firstName() correctly uses Greek first names.

### Minimal reproduction code

```
faker.setLocale("el");console.log(`First name: ${faker.person.firstName()}, Full name: ${faker.person.fullName()}`)
```

```
Some example outputs:

First name: Άγγελος, Full name: Jerome Βονόρτας
First name: Αναστάσιος, Full name: Gayle Καλύβας
First name: Αντώνης, Full name: Julie Κορνάρος
First name: Αριστείδης, Full name: Nicholas Καλλιγάς IV
First name: Λεωνίδας, Full name: Jenny Δεσποτόπουλος
First name: Μιχαήλ, Full name: Richard Αγγελόπουλος
First name: Μιχαήλ, Full name: Κυρία Kim Αλεξάκης
First name: Σπύρος, Full name: Kellie Παπαδόπουλος I
First name: Στέφανος, Full name: Gladys Βιτάλη
First name: Σωτήριος, Full name: Levi Αυγερινός (επώνυμο)
```

### Environment Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 42.11 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 98.0
    Safari: 16.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by ST-DDT** [comment] 2022-11-15 22:03
Duplicate of https://github.com/faker-js/faker/issues/547

**Closed as completed by ST-DDT** 2022-11-15 22:03 UTC
Labels: c: bug, c: locale, m: person

**Comment by matthewmayer** [comment] 2022-11-27 11:57
@ST-DDT can this be reopened? This is not the same as #547 - this is a related but different issue, which happens when a locale ONLY has generic names, not male/female names. #547 happened for locales with male/female names but NO generic names.

**Comment by matthewmayer** [comment] 2022-11-27 12:13
these locales have first_name but no male_first_name and female_first_name
```
de_AT
de_CH
el
en_AU
en_AU_ocker
en_IN
es_MX
ge
ko
ne
nl_BE
zh_TW
```

In a lot of cases it would be pretty simple to manually seperate into male and female, for example https://github.com/faker-js/faker/blob/next/src/locales/en_AU/person/first_name.ts is male for lines 1-101 and female for lines 102-201. So we could do that and then create the synthetic generic list like in my PR for #547

**Comment by ST-DDT** [comment] 2022-11-27 14:26
#547 is about a structural error in the locales which has basically 2 symptoms. 
The original one reported in #547 and this one.
Please note, the issue is not only about first names, but also last names, middle names etc...

See for our decision: https://github.com/faker-js/faker/issues/547#issuecomment-1240937734

**Comment by matthewmayer** [comment] 2022-11-27 15:09
Hmm, i'm not sure how that decision would actually fix the bug though? Because if a locale doesn't contain gendered first names, won't it continue to fallback to en?

**Comment by matthewmayer** [comment] 2022-11-27 15:19
Note this doesn't typically affect last names, because `en` doesn't have gendered last names. It does in theory affect middle names, but since fullName doesn't use middle name, that rarely comes up.

**Comment by ST-DDT** [comment] 2022-11-27 18:12
> Hmm, i'm not sure how that decision would actually fix the bug though? Because if a locale doesn't contain gendered first names, won't it continue to fallback to en?

Yes, because it would then fallback to the gendered version of the same locale.
