### ISSUE TITLE
Russian locale partially not working in Name module

### ISSUE THREAD

**Issue by SkifAlef** [faker-js/faker#1352] opened 2022-09-07 11:13 UTC
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/main/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

Faker doesn't use locale (at least 'ru') when I'm using name.firstName() or lastName() without sex parameter.
I.e. `faker.name.lastName('female')` generates valid Russian last name, for example, Иванова
But `faker.name.lastName()` generates fallback English last name like Smith

### Minimal reproduction code

https://stackblitz.com/edit/faker-js-demo-lvrleu?file=index.ts

### Environment Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700KF
    Memory: 38.74 GB / 63.85 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @faker-js/faker: ^7.5.0 => 7.5.0
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

yarn

**Comment by Shinigami92** [comment] 2022-09-07 11:16
Please provide a `src/locales/ru/name/first_name.ts` and `src/locales/ru/name/last_name.ts`

**Comment by ST-DDT** [comment] 2022-09-07 11:25
Duplicate of https://github.com/faker-js/faker/issues/547

**Closed by ST-DDT** 2022-09-07 11:25 UTC
Labels: c: bug, s: pending triage
