### ISSUE TITLE
faker.internet.url sometimes returns invalid urls

### ISSUE THREAD

**Issue by vegrituk** [faker-js/faker#502] opened 2022-02-17 15:22 UTC
### Describe the bug

We use fake urls with `faker.internet.url()` in our unit tests which are then passed to `new URL()`. Sometimes, the latter throws a TypeError and it looks the created urls are just invalid:
 `TypeError: Invalid URL: https://artistic-dump truck.info`
or
`TypeError: Invalid URL: https://heavenly-creme brulee.name`
There seem to be spaces where obviously none should be.

### Reproduction

There's no reliable way to reproduce this. Most of the time, the tests just pass fine. So probably create tons of fake urls and see if something comes up.

### Additional Info

Version: ^6.0.0-alpha.5

**Comment by ST-DDT** [comment] 2022-02-17 15:37
Fixed in https://github.com/faker-js/faker/pull/258 (contained in [alpha 6](https://github.com/faker-js/faker/releases/tag/v6.0.0-alpha.6))

Duplicate of https://github.com/faker-js/faker/issues/256

**Closed by ST-DDT** 2022-02-17 15:37 UTC
Labels: pending triage
