### ISSUE TITLE
domainWord returns jalapeño

### ISSUE THREAD

**Issue by pvatterott** [faker-js/faker#1538] opened 2022-11-07 21:48 UTC
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

I just migrated from `faker` and we use `internet.domainWord` to fake out customer subdomains in tests. After the migration, tests are intermittently failing because we get subdomains with the word `jalapeño` in them, which are not valid.

The simplest fix would be to remove `jalapeño` from the locale file [here](https://github.com/faker-js/faker/blob/8bf716225e9c5b3ce5c968511886b9141d5c918d/src/locales/en/word/noun.ts#L3247). With a quick scan, I don't see that there are other words with non-ascii characters in them. I would be happy to provide a PR, but I'm not sure of the implications of removing things from that file / whether changing the `domainWord` [implementation](https://github.com/faker-js/faker/blob/09e835664add0a342dd089f31bbae7d880198493/src/modules/internet/index.ts#L292) would be preferred.

We have a workaround, so not a big deal, but wanted to file while it is top of mind

### Minimal reproduction code

`faker.domainWord()`

### Environment Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) x64 Apple M1 Pro
    Memory: 20.50 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Firefox: 106.0.5
    Safari: 16.0
  npmPackages:
    @faker-js/faker: 7.6.0 => 7.6.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

yarn

**Comment by ST-DDT** [comment] 2022-11-07 22:06
Thanks for bringing this to our attention.
We already have an issue that we use to keep track of this issue.

Duplicate of #1105  (#1520)

**Closed as completed by ST-DDT** 2022-11-07 22:06 UTC
Labels: c: bug
