### ISSUE TITLE
Using a seed produces different data when updating from 7.5.0 to 7.6.0

### ISSUE THREAD

**Issue by jansepke** [faker-js/faker#1489] opened 2022-10-26 14:20 UTC
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

We are using faker to generate random but stable values. We are calculating a different but stable seed for every data set and then use faker to generate data. Since we updated faker from version 7.5.0 to 7.6.0 we will get a different set of generated results for the same seed. The results are still stable for version 7.6.0 but changed compared to all the versions below 7.6.0.

I attached sample code and the generated results with both versions.

Maybe it could be related to very big seed numbers.

### Minimal reproduction code

```javascript
const { faker } = require('@faker-js/faker/locale/de');

faker.seed(49505152535455560000);
console.log(faker.address.city());
console.log(faker.address.zipCode());
console.log(faker.address.streetName());
console.log(faker.phone.number());
```

result with faker 7.5.0:
```
Schwarzmeierland
87438
Ober dem Hof
+49-073-6267085
```

result with faker 7.6.0:
```
Schwarzmeierland
98743
Sperberweg
+49-507-3626708
```

### Environment Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (2) x64 AMD EPYC 7571
    Memory: 3.59 GB / 7.69 GB
    Container: Yes
    Shell: 3.5.1 - /usr/bin/fish
  npmPackages:
    @faker-js/faker: ^7.6.0 => 7.6.0
```

### Which module system do you use?

- [X] CJS
- [ ] ESM

### Used Package Manager

npm

**Comment by Shinigami92** [comment] 2022-10-26 15:19
Closing as duplicate of
- #1464

**Closed as completed** 2022-10-26 15:19 UTC
Labels: duplicate
