### ISSUE TITLE
typescript: update to v6.1.0 throws 'Cannot find module '@faker-js/faker' or its corresponding type declarations.'

### ISSUE THREAD

**Issue by jechrzFoko** [faker-js/faker#715] opened 2022-03-28 20:45 UTC
### Describe the bug

Hello,

After updating to the latest version of v6.1.0, doing a npm run build fails with a message  "_Cannot find module '@faker-js/faker' or its corresponding type declarations.'_ " error within our typescript project.

We attempted to reinstall the module via 'npm install @faker-js/faker --save-dev' and no such luck as the npm run build still fails with the above error.

### Reproduction

On typescript project:
1. install latest @faker-js/faker v6.1.0
2. execute 'npm run build' command

Actual Results:

npm run build fails with the following error:

```
error TS2307: Cannot find module '@faker-js/faker' or its corresponding type declarations.
```

### Additional Info

Our current codebase uses typescript and we are currently on v6.0.0 (which works). Below is the tsconfig settings and how we import faker within the project:

tsconfig.json:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "esModuleInterop": true,
        "target": "ES2020",
        "moduleResolution": "Node",
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "outDir": "dist",
        "baseUrl": "."
    },
    "include": ["src/**/*.ts", "node_modules/@types"],
    "exclude": ["node_modules/@types/node"]
}
```

how we import faker:
```
import { faker } from '@faker-js/faker';
```

**Comment by import-brain** [comment] 2022-03-28 21:03
duplicate of #711

**Closed by import-brain** 2022-03-28 21:03 UTC
Labels: s: pending triage
