### ISSUE TITLE
Add phone.number generation options

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#1542] opened 2022-11-07 23:02 UTC
### Clear and concise description of the problem

Currently the phone.number method generates phone numbers in various formats.
However, the usually the phone number inputs require specific input formats e.g. an international telephone number.

### Suggested solution

It would be nice if it is possible to be more specific which addresses should be generated.

- `type?: 'landline' | 'cell-phone'`
- `format?: 'international' | 'national'`

It is not a goal to generate phone numbers that are normalized beyond the given options. So the user might still have to strip whitespace or other "human" additions.

### Alternative

- https://github.com/faker-js/faker/issues/1541

**Comment by mcmxcdev** [comment] 2023-02-28 08:03
We actually have a real-world issue related to this:

We use [react-phone-number-input](https://gitlab.com/catamphetamine/react-phone-number-input) with a restriction for `country=US`, but `faker.phone.number()` can't be configured easily to give us US locale only.

Therefore, we encounter this warning within our unit tests:

```
console.error
      [react-phone-number-input] Expected phone number +17427794379 to correspond to country US but in reality it corresponds to country CA.
```

**Comment by matthewmayer** [comment] 2023-02-28 08:22
> We actually have a real-world issue related to this:
> 
> We use [react-phone-number-input](https://gitlab.com/catamphetamine/react-phone-number-input) with a restriction for `country=US`, but `faker.phone.number()` can't be configured easily to give us US locale only.
> 
> Therefore, we encounter this warning within our unit tests:
> 
> ```
> console.error
>       [react-phone-number-input] Expected phone number +17427794379 to correspond to country US but in reality it corresponds to country CA.
> ```

if you do `faker.locale = 'en_US'`, i think you should only get US area codes, not including 742? https://github.com/faker-js/faker/blob/next/src/locales/en_US/phone_number/area_code.ts

**Comment by mcmxcdev** [comment] 2023-02-28 08:37
I guess I can just wait for https://github.com/faker-js/faker/pull/1735 to be merged, which makes `en_US` the default and kicks out all other locales?

**Comment by matthewmayer** [comment] 2023-02-28 08:40
There's a difference between the default locale `en` which is generic for worldwide English, and `en_US` which is specific for the United States, #1735 won't change that.

So `en` if you want a mix of phone numbers from different countries, `en_US` for US and `en_GB` for Great Britain, etc.

**Comment by mcmxcdev** [comment] 2023-02-28 15:44
Hmm, the problem is we use `faker.phone.number('+1##########')` currently which then doesn't care about the locale set.

When switching to use `faker.phone.number()`, all kinds of formats are generated like `860.297.1343` or `572-614-7168 x1623` as described in the original issue description, which then doesn't work with our code.

**Comment by ST-DDT** [comment] 2023-02-28 20:58
> When switching to use `faker.phone.number()`, all kinds of formats are generated like `860.297.1343` or `572-614-7168 x1623` as described in the original issue description, which then doesn't work with our code.

This issue is exactly there for that (to add options to get only the expected formats without manually passing it to the method).

**Comment by mcmxcdev** [comment] 2023-03-01 06:37
Yeah, perfect! Then I will eagerly await the new functionality ;)

I can also offer to test changes out with our codebase if you guys have the need for it.

**Comment by matthewmayer** [comment] 2023-03-01 09:43
> It is not a goal to generate phone numbers that are normalized beyond the given options

perhaps `format = national` should generate "messy" numbers with various spaces, hyphens, extensions, etc, but `format=international` should only generate numbers in the standard https://en.wikipedia.org/wiki/E.123 notation without spaces ie +{COUNTRYCODE}{NATIONALNUMBER} as that is a common way to store phone numbers in a database?

**Comment by ST-DDT** [comment] 2023-03-01 23:54
> but `format=international` should only generate numbers in the standard [en.wikipedia.org/wiki/E.123](https://en.wikipedia.org/wiki/E.123) notation without spaces ie +{COUNTRYCODE}{NATIONALNUMBER} as that is a common way to store phone numbers in a database?

This might be how you write it to your database, but that is not how your users will put it into your input fields.
(I remember some big platform, I don't remember which one (google, github or ...) requested me to input my number with a leading 0 even if they showed the +12 country selector at the front.)
Should we add a `clean` or similar parameter that can be used to strip these "formatting" characters?

**Comment by matthewmayer** [comment] 2023-03-02 00:36
That would work too.

**Comment by ST-DDT** [comment] 2023-03-16 17:24
**Team Decision**

- We want this, but we will decide later how the actual implementation will work.
- This will effectively merge phone and cell phone locale data.

We might add a parameter that allows choosing whether the number should follow the standard or was "input" by a user.

**Comment by wyardley** [comment] 2023-09-22 04:36
It would be nice if at least a few options were available before the deprecation took effect.
We have an simple use case like `faker.phone.number('##########')`, which I think would be hard to replicate until this is complete?

**Comment by matthewmayer** [comment] 2023-09-22 05:11
> It would be nice if at least a few options were available before the deprecation took effect. We have an simple use case like `faker.phone.number('##########')`, which I think would be hard to replicate until this is complete?

the direct replacement for `faker.phone.number('##########')` is `faker.helpers.replaceSymbolWithNumber('##########')` - maybe the deprecation message should be modified to make that clearer?

**Comment by wyardley** [comment] 2023-09-22 05:17
> maybe the deprecation message should be modified to make that clearer?

Yes, that would be helpful, if it's not too niche, or link to more docs somewhere?

Will the behavior differ at all between those two (in terms of which numbers can show up in which positions)? I'd thought of using string methods on the number, but that seems messier, and I don't like seeing the deprecation errors.

**Comment by matthewmayer** [comment] 2023-09-22 05:18
Nope, if you pass a format parameter to faker.phone.number it directly passes it to the replaceSymbolWithNumber method at the moment

**Comment by matthewmayer** [comment] 2023-09-22 05:58
For the original issue, i think the new API should be kept fairly minimal to start with, given the number of possible different "axes" which would make this hard to localize and test:
* cleanliness ie do you want raw numbers like +XXXXXXX, consistently formatted like (XXX) XXX-XXXX or a variety of human/messy formats
* include or dont include country codes or both?
* include or dont include extensions?
* include mobile numbers, landline numbers or both (and in some locales you can't tell the difference e.g. en-US)

So maybe there's only a single parameter like "style" = `human | raw | national` initially which maps to the combination of these which we think are most likely to be useful, and each of those points to a seperate definition file, e.g.

* human (default) has a big mix of formats, with and without country codes, extensions, dashes and punctuation. This is useful if you are testing user input.
* raw is always in international format with no spaces or extensions e.g. +XXXXXXXXX. This is useful if you are inserting directly into a database
* national is in a standardized national format for the locale ie assumes that the data has been preprocessed e.g. 0XX XXX-XXXX. This is useful if you are showing in a mockup.

Then if users say "hey we really need a new style for this use case" it can be added without worrying too much about breaking existing functionality, you would just need to add a new definition file for the style.

**Comment by ST-DDT** [comment] 2023-09-22 06:26
> It would be nice if at least a few options were available before the deprecation took effect. We have an simple use case like `faker.phone.number('##########')`, which I think would be hard to replicate until this is complete?

IMO this patter can be very easily generated by `faker.string.numeric(9)` or is that just an example and the pattern is more complex?

**Comment by ST-DDT** [comment] 2023-09-22 06:29
> the direct replacement for `faker.phone.number('##########')` is `faker.helpers.replaceSymbolWithNumber('##########')`

IIRC that method is going to get deprecated as well. See #1994 for more details.

**Comment by wyardley** [comment] 2023-09-22 06:35
In some cases we have a `+` as well, which works fine with the example above.

But the examples for a possible implementation above seem preferable if / when they’re implemented.

**Comment by matthewmayer** [comment] 2023-09-22 06:36
hmm, now i think about it, i think while saying that method  "is mostly a black box that does some arbritary char -> digit transformations" is true, those are generally transformations which are useful for phone numbers. So maybe it would make sense to not deprecate it, for example if you want phone numbers in a non-standard but fixed pattern say `(!##) !##-####` that would be quite hard to achieve with other methods.

**Comment by ST-DDT** [comment] 2023-09-22 06:47
> for example if you want phone numbers in a non-standard but fixed pattern say `(!##) !##-####` that would be quite hard to achieve with other methods.

The issue there is that `!` is tailored specifically for the US usage. Other locales have other needs.

It can easily achieved with js string.replace, faker.string.numeric, or faker.helpers.fromRegexp.
You can find more details about them here: https://fakerjs.dev/api/

**Comment by matthewmayer** [comment] 2023-09-22 07:26
sure, but i would say there is no hurry to deprecate replaceSymbolWithNumber at least until we have more flexible options for phone.number() - that way anyone who is currently using a fixed format pattern has the option to either switch to one of the new patterns, or build their own.

**Comment by matthewmayer** [comment] 2023-09-22 07:39
Anyway this discussion is a bit offtopic, lets discuss deprecation further on https://github.com/faker-js/faker/issues/1994 this issue can be for the future options for the phone.number method.

**Comment by Amine27** [comment] 2023-09-22 14:25
> > It would be nice if at least a few options were available before the deprecation took effect. We have an simple use case like `faker.phone.number('##########')`, which I think would be hard to replicate until this is complete?
> 
> the direct replacement for `faker.phone.number('##########')` is `faker.helpers.replaceSymbolWithNumber('##########')` - maybe the deprecation message should be modified to make that clearer?

Sorry, but the two methods are not the same, replacing them in our application results in tests failures.

**Comment by ST-DDT** [comment] 2023-09-22 14:38
Well, AFAICT they are:

https://github.com/faker-js/faker/blob/5e900d2df2e17be58991f3d0f2290ed4cd8a33ff/src/modules/phone/index.ts#L36-L43

Unless you don't always provide the format or the JS runtime processes the fallback path even though it doesn't have to.

**Comment by matthewmayer** [comment] 2023-09-22 15:57
> > the direct replacement for `faker.phone.number('##########')` is `faker.helpers.replaceSymbolWithNumber('##########')` - maybe the deprecation message should be modified to make that clearer?
> 
> Sorry, but the two methods are not the same, replacing them in our application results in tests failures.

Seems identical for a given seed:

```js
faker.seed(123); faker.helpers.replaceSymbolWithNumber('##########')
// 6724265774

faker.seed(123); faker.phone.number('##########')
// 6724265774
```

**Comment by matthewmayer** [comment] 2023-09-27 02:28
> For the original issue, i think the new API should be kept fairly minimal to start with, given the number of possible different "axes" which would make this hard to localize and test:
> 
> * cleanliness ie do you want raw numbers like +XXXXXXX, consistently formatted like (XXX) XXX-XXXX or a variety of human/messy formats
> * include or dont include country codes or both?
> * include or dont include extensions?
> * include mobile numbers, landline numbers or both (and in some locales you can't tell the difference e.g. en-US)
> 
> So maybe there's only a single parameter like "style" = `human | raw | national` initially which maps to the combination of these which we think are most likely to be useful, and each of those points to a seperate definition file, e.g.
> 
> * human (default) has a big mix of formats, with and without country codes, extensions, dashes and punctuation. This is useful if you are testing user input.
> * raw is always in international format with no spaces or extensions e.g. +XXXXXXXXX. This is useful if you are inserting directly into a database
> * national is in a standardized national format for the locale ie assumes that the data has been preprocessed e.g. 0XX XXX-XXXX. This is useful if you are showing in a mockup.
> 
> Then if users say "hey we really need a new style for this use case" it can be added without worrying too much about breaking existing functionality, you would just need to add a new definition file for the style.

Comparing to https://www.npmjs.com/package/libphonenumber-js

* `human` would be like we have now
* `national` would be like the result of `formatNational()`
* `raw` would be like the result of `.getURI()`, but without the `tel:` prefix

<img width="748" alt="image" src="https://github.com/faker-js/faker/assets/152770/d458ab9e-2382-4794-ada9-49e8dd2bcfd9">

**Comment by Gyran** [comment] 2023-11-02 10:19
My use case is mostly providing default data from my database models so for me it would be nice to get a "parsed" phone number and only mobile numbers.
I really like the "no arguments" approach with faker so something like this would be nice for me.
```
faker.phone.mobile(); // only mobile numbers
faker.phone.landline(); // landline
faker.phone.number(); // mix of everything
```

I can see the use case for the "human input" format as well, but that is currently not something I use it for. But an argument with "style" I guess could work. Guess that is applicable to many different things. I looked in the documentation for amount for example, which also is prone to many different input formats.

But as I said, my use case is mostly for output so I would want a consistent format, but it would be nice to be able to generate "input" data as well.

**Comment by banshee** [comment] 2023-12-12 23:02
> faker.phone.mobile

Just FYI, there's no way in the North American Numbering Plan to distinguish between mobile and landlines.  https://en.wikipedia.org/wiki/List_of_North_American_Numbering_Plan_area_codes

**Comment by matthewmayer** [comment] 2023-12-13 11:11
> So maybe there's only a single parameter like "style" = `human | raw | national` initially which maps to the combination of these which we think are most likely to be useful, and each of those points to a seperate definition file, e.g.
> 
> 
> 
> * human (default) has a big mix of formats, with and without country codes, extensions, dashes and punctuation. This is useful if you are testing user input.
> 
> * raw is always in international format with no spaces or extensions e.g. +XXXXXXXXX. This is useful if you are inserting directly into a database
> 
> * national is in a standardized national format for the locale ie assumes that the data has been preprocessed e.g. 0XX XXX-XXXX. This is useful if you are showing in a mockup.
> 
> 
> 
> Then if users say "hey we really need a new style for this use case" it can be added without worrying too much about breaking existing functionality, you would just need to add a new definition file for the style.
> 
> 

Would people be OK with me proceeding with a PR to introduce this "style" parameter?

**Comment by ST-DDT** [comment] 2023-12-13 14:29
> Would people be OK with me proceeding with a PR to introduce this "style" parameter?

Yes, although this will probably end up in v9.x. As I want to wrap up v8.x and start with v9.0.

**Closed as completed** 2024-03-12 11:01 UTC
Labels: c: feature, p: 1-normal, s: accepted, m: phone

**Comment by alexcroox** [comment] 2024-04-08 07:56
+1 for generating mobile (cell) numbers. My registration form only allows mobile numbers and currently `fake.phone.number()` only generates landline numbers (for fakerEN_GB):

GB Landline: 02392 232456
GB Mobile: 07742 578125 (always starts with 07)

Edit: solved temporarily with `faker.helpers.fromRegExp(/07[0-9]{9}/)`

**Comment by x9sim9** [comment] 2024-05-07 10:06
considering this has already been solved very well by the FFaker gem would it not make sense to copy their implementation since this already shares the same name and has alot of crossover already and solves all the issues mentioned in this thread?

https://www.rubydoc.info/github/ffaker/ffaker/FFaker/PhoneNumber

**Comment by matthewmayer** [comment] 2024-05-07 11:01
> considering this has already been solved very well by the FFaker gem would it not make sense to copy their implementation since this already shares the same name and has alot of crossover already and solves all the issues mentioned in this thread?
> 
> 
> 
> https://www.rubydoc.info/github/ffaker/ffaker/FFaker/PhoneNumber

It looks like FFaker has quite a different philosophy for dealing with localisation

Eg the different localisations for phone numbers in FFaker contain Ruby code. 

Eg https://github.com/ffaker/ffaker/blob/main/lib/ffaker/phone_number_au.rb

Whereas in faker-js the localisations are typically simple data and any logic is kept in centralised methods. 

That would make it hard to port the logic directly.

**Comment by matthewmayer** [comment] 2024-05-07 14:05
As this issue is already closed, please add any further suggestions for phone improvements here: https://github.com/faker-js/faker/discussions/2883 this will ensure it doesn't get lost.
