### ISSUE TITLE
[ERROR] The entry point "mock/table.ts.timestamp-1710847630001.mjs" cannot be marked as external

### ISSUE THREAD

**Issue by sun-unc** [faker-js/faker#2762] opened 2024-03-19 12:18 UTC
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

当我通过pnpm run dev 启动项目时，偶尔（大概率）会报错，但是项目能正常运行起来
```
✘ [ERROR] The entry point "mock/table.ts.timestamp-1710847630001.mjs" cannot be marked as external

Error: Build failed with 1 error:
error: The entry point "mock/table.ts.timestamp-1710847630001.mjs" cannot be marked as external
    at failureErrorWithLog (/Users/sun/Code/Vue/WebDevPractice/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/sun/Code/Vue/WebDevPractice/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1059:25
    at runOnEndCallbacks (/Users/sun/Code/Vue/WebDevPractice/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1486:45)
    at buildResponseToResult (/Users/sun/Code/Vue/WebDevPractice/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1057:7)
    at /Users/sun/Code/Vue/WebDevPractice/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (/Users/sun/Code/Vue/WebDevPractice/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/Users/sun/Code/Vue/WebDevPractice/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/Users/sun/Code/Vue/WebDevPractice/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
```

### Minimal reproduction code

/mock/table.ts
```
import { defineMock } from "vite-plugin-mock-dev-server";
import { faker } from "@faker-js/faker";

const data = [
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
  {
    date: faker.date.past(),
    name: faker.internet.userName(),
    address: faker.location.city(),
  },
];
export default defineMock({
  url: "/api/table",
  body: ({ body: { page, pageSize } }) => {
    return {
      total: data.length,
      data: data.slice((page - 1) * pageSize, page * pageSize),
    };
  },
  delay: 1000,
});
```

### Environment Info

```shell
- OS:MacOS M1
- Node:v18.19.1
- packageManager:pnpm
- vite:^5.0.12
- faker-js/faker: ^8.4.1
- vite-plugin-mock-dev-server: ^1.4.7
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

pnpm

**Comment by ST-DDT** [comment] 2024-03-19 13:26
Which version of Faker are you using?

**Comment by sun-unc** [comment] 2024-03-21 11:51
> Which version of Faker are you using?

"@faker-js/faker": "^8.4.1"

**Comment by xDivisionByZerox** [comment] 2024-03-22 10:04
I cannot reproduce this. The code provided in your "Minimal reproduction code" does nothing (do I need to build something?, must this be run in a vite project?, etc.). Please read [how to create a minimal, reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) or [Wtf is a minimum reproduction?](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction).
Additionally, you might want to provide a [Stackblitz](https://stackblitz.com/edit/faker-js-demo?file=index.ts) link. This way we simply need to click a link to help you.

**Comment by ST-DDT** [comment] 2024-04-01 09:40
Closing this as not reproducible.
If a reproduction is provided we can reopen this.

**Closed as not planned by ST-DDT** 2024-04-01 09:40 UTC
Labels: c: bug, s: awaiting more info
