### ISSUE TITLE
Error: Cannot find module '/workspace/tgyi_mysql/node_modules/@faker-js/faker/dist/cjs/index.js'

### ISSUE THREAD

**Issue by tgyi1697** [faker-js/faker#711] opened 2022-03-28 20:00 UTC
### Describe the bug

Using faker I got the following error:
Error: Cannot find module '/workspace/tgyi_mysql/node_modules/@faker-js/faker/dist/cjs/index.js'

### Reproduction

After installing faker I have the following directories:
node_modules
node_modules/@faker_js
node_modules/@faker_js/faker

I made a quite simple app.js file:

const { faker } = require('@faker-js/faker'); 
console.log(faker.internet.email()); 

And then:
Error: Cannot find module '/workspace/tgyi_mysql/node_modules/@faker-js/faker/dist/cjs/index.js'

I have no node_modules/@faker-js/faker/dist/ and node_modules/@faker-js/faker/dist/cjs/ directories, and there is no index.js at all.

Thanks

**Comment by racedaemon** [comment] 2022-03-28 20:10
Had a similar error in a typescript project that worked yesterday. Rolling back to version 6.0.0 fixed it for me.

**Comment by ST-DDT** [comment] 2022-03-28 20:33
Which faker/node/npm/typescript versions are you using?

**Comment by tgyi1697** [comment] 2022-03-28 20:36
faker: 6.1.0 (now I use 6.0.0)
node: 16.14.2
npm: 8.5.5

**Comment by ST-DDT** [comment] 2022-03-28 20:48
I can confirm this issue using our playground.

**Comment by ST-DDT** [comment] 2022-03-28 20:56
We are working on it.

**Comment by ST-DDT** [comment] 2022-03-28 21:05
Will be fixed in https://github.com/faker-js/faker/pull/716

**Closed** 2022-03-28 21:10 UTC
Labels: c: bug, p: 3-urgent, s: accepted

**Comment by ST-DDT** [comment] 2022-03-28 21:14
The issue has been resolved in v6.1.1.
Sorry for the trouble.
We will investigate ways to ensure the same issues does not happen again.

**Comment by Shinigami92** [comment] 2022-03-29 05:48
> The issue has been resolved in v6.1.1. Sorry for the trouble.

Thanks to @ST-DDT that he managed the communication part yesterday, it was really late for us.
I forgot to run `pnpm run build` because all my other projects are doing that on publish automatically so I was used to that.

> We will investigate ways to ensure the same issues does not happen again.

I now added https://github.com/faker-js/faker/blob/62dcfc9658e6d3ee23b9e674d10b9a229b026d0e/package.json#L76 but even this could not solve every problem. Even a bundled dist folder could contain e.g. invalid bundled code somehow. Therefor we may need to test our package after we released it.
We also have this issue: #268 but I don't know how to implement that (at least in an easy way)

**Comment by lawrenceegr** [comment] 2024-05-04 05:25
I don't know if anyone still experiences this in `"faker": "^6.6.6",`. After inspecting the `faker` package in node_modules/faker/package.json I found that it has `"main": "index.js"`. But the `index.js` file is not present. That's why when I try to run my expressJS server I get this error.

Error: Cannot find module '/home/boltext/Code/Advanced/iot-dashboard/server/node_modules/faker/index.js'

Can someone please help me on how I'll resolve this issue?

**Comment by ST-DDT** [comment] 2024-05-04 05:35
Faker has been renamed to [`@faker-js/faker`](https://www.npmjs.com/package/@faker-js/faker)
It also has a lot of updates and improvements.
Latest stable is `v8.4.1`.
We also have a new website: https://fakerjs.dev/

**Comment by lawrenceegr** [comment] 2024-05-04 05:49
> Faker has been renamed to [`@faker-js/faker`](https://www.npmjs.com/package/@faker-js/faker) It also has a lot of updates and improvements. Latest stable is `v8.4.1`. We also have a new website: https://fakerjs.dev/

I see, thanks! Lmee take take a look at it
