### ISSUE TITLE
Add plugin support for modules

### ISSUE THREAD

**Issue by frankieali** [faker-js/faker#2887] opened 2024-05-08 15:56 UTC
### Clear and concise description of the problem

Integrate plug-in support for faker so 3rd party modules can be added from outside the faker-js source project. This would allow for others to develop modules independent of faker-js and could also allow for internal modules to be released on their own release cycles if so desired.

### Suggested solution

My suggestion would be to integrate hooks into the source code that would allow registering 3rd party modules. These hooks would allow developers to register their module, the module definitions and the module locales. The plugins would be passed into the faker constructor and the hooks would then iterate over the array of available plugins to register them.

### Additional context

Some modules, such as the plant module, are being help up by community interest. A plug-in solution would allow people to develop at their own pace and make their own community contributions.

**Comment by xDivisionByZerox** [comment] 2024-05-08 16:04
We are already tracking a potential plugin system in #704. I'll close this as duplicate.

**Closed as not planned by xDivisionByZerox** 2024-05-08 16:04 UTC
Labels: c: feature, duplicate

**Comment by xDivisionByZerox** [comment] 2024-05-08 16:06
Duplicate of #704
